import IconPokeball from "@/components/icons/IconPokeball";
import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";
// import HeaderUserInfo from "@/components/HeaderUserInfo";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { getSession } from "@auth0/nextjs-auth0";

export const metadata: Metadata = {
  title: "Pokeland",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();

  return (
    <html lang="en">
      <UserProvider>
        <body className="p-4">
          <header className="border-gray-800 border-b-2 mb-2 pb-2">
            <h1 className="h1">
              <a href="/">
                <IconPokeball style={{ width: "40px", display: "inline" }} />{" "}
                Pokeland
              </a>
            </h1>
            <nav>
              <Link className="link" href="/pokemon">
                Pokemon
              </Link>{" "}
              <Link className="link" href="/about">
                About
              </Link>{" "}
              <Link className="link" href="/contact">
                Contact
              </Link>
            </nav>
            <>
              {session && (
                <>
                  Logged in: {session.user?.name}{" "}
                  <a href="/api/auth/logout" className="btn">
                    Sign out
                  </a>
                </>
              )}
              {/* {:else if altSession}
    Logged in: {altSession.user?.name}
    <button on:click={() => signOut()} className="btn">Sign out</button> */}
              {!session && (
                <>
                  Logged out{" "}
                  <a href="/api/auth/login" className="btn">
                    Sign In with Auth0
                  </a>
                </>
              )}
            </>
          </header>

          <main>{children}</main>

          <footer className="border-gray-800 border-t-2 mt-8 pt-2">
            <small>
              Pokeball icon by Curve from{" "}
              <a
                href="https://thenounproject.com/browse/icons/term/pokeball/"
                target="_blank"
                title="Pokeball Icons"
              >
                Noun Project
              </a>{" "}
              (CC BY 3.0)
            </small>
          </footer>
        </body>
      </UserProvider>
    </html>
  );
}
