import IconPokeball from "@/components/icons/IconPokeball";
import "./globals.css";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Pokeland",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="p-4">
        <header className="border-gray-800 border-b-2 mb-2 pb-2">
          <h1 className="h1">
            <a href="/">
              <IconPokeball style={{ width: "40px", display: "inline" }} />{" "}
              Pokeland
            </a>
          </h1>
          <nav>
            <Link className="link" href="/pokemon">
              Pokemon
            </Link>{" "}
            <Link className="link" href="/about">
              About
            </Link>{" "}
            <Link className="link" href="/contact">
              Contact
            </Link>
          </nav>
          {/* {#if $page.data.session}
    Logged in: {$page.data.session.user?.name}
    <button on:click={() => signOut()} className="btn">Sign out</button>
  {:else if altSession}
    Logged in: {altSession.user?.name}
    <button on:click={() => signOut()} className="btn">Sign out</button>
  {:else}
    Logged out
    <!-- Auth.js core doesn't support federated log out yet. The user will be logged out of the app but not Auth0. https://github.com/nextauthjs/next-auth/issues/1384 -->
    <!-- we can get around it by force-showing auth0 login prompt -->
    <!-- this is a security issue -->
    <!-- we could manually work around it: https://github.com/nextauthjs/next-auth/issues/836 -->
    <button className="btn" on:click={() => signIn('auth0', undefined, { prompt: 'login' })}
      >Sign In with Auth0</button
    >
  {/if} */}
        </header>

        <main>{children}</main>

        <footer className="border-gray-800 border-t-2 mt-8 pt-2">
          <small>
            Pokeball icon by Curve from{" "}
            <a
              href="https://thenounproject.com/browse/icons/term/pokeball/"
              target="_blank"
              title="Pokeball Icons"
            >
              Noun Project
            </a>{" "}
            (CC BY 3.0)
          </small>
        </footer>
      </body>
    </html>
  );
}
